version: 2
updates:
  # Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "deps"
      include: "scope"
    reviewers:
      - "Mindgamesnl"
    labels:
      - "dependencies"
    open-pull-requests-limit: 5

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "ci"
      include: "scope"
    reviewers:
      - "Mindgamesnl"
    labels:
      - "dependencies"
      - "github-actions"
    open-pull-requests-limit: 5
